name: Build and Scan Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    env:
      FRONTEND_IMAGE: frontend
      BACKEND_IMAGE: backend
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend image
        run: |
          docker build -t $FRONTEND_IMAGE:$IMAGE_TAG ./frontend

      - name: Build backend image
        run: |
          docker build -t $BACKEND_IMAGE:$IMAGE_TAG ./backend

      - name: Scan frontend image with Trivy (ignore result)
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --severity CRITICAL,HIGH \
            $FRONTEND_IMAGE:$IMAGE_TAG || true

      - name: Scan backend image with Trivy (ignore result)
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --severity CRITICAL,HIGH \
            $BACKEND_IMAGE:$IMAGE_TAG || true
